version: "3"

services:
  extract_load:
    build:
      context: ./extract_load
      dockerfile: Dockerfile
    command: ["python", "player_statistics.py"]
    volumes:
      - ./keys/storageKeyFile.json:/credentials/keyfile.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/keyfile.json
    networks:
      - sports_data
networks:
  sports_data:
    driver: bridge
